### ISSUE TITLE
can't convert non-string with explicit base

### ISSUE THREAD

**Issue by santzi** [Kefkius/electrum-nmc-server#1]
Hi,

I planning to start running Namecoin Electrum server, but it does not seems to work.
I downloaded sources from master branch.

Python crashed immediately when I started electrum server.
Namecoin Daemon is up and running.

INFO:electrum:Starting Electrum-NMC server on 192.168.1.33
INFO:electrum:initializing database
INFO:electrum:UTXO tree root hash: 5df6e0e2761359d30a8275058e299fcc0381534545f55cf43e41983f5d4c9456
INFO:electrum:Coins in database: 0
INFO:electrum:catching up missing headers: -1 0
Traceback (most recent call last):
  File "./run_electrum_nmc_server", line 257, in <module>
    chain_proc = BlockchainProcessor(config, shared)
  File "/home/jeppa/Downloads/git/electrum-nmc-server/src/blockchain_processor.py", line 66, in **init**
    self.init_headers(self.storage.height)
  File "/home/jeppa/Downloads/git/electrum-nmc-server/src/blockchain_processor.py", line 168, in init_headers
    header = self.get_header(height)
  File "/home/jeppa/Downloads/git/electrum-nmc-server/src/blockchain_processor.py", line 145, in get_header
    return self.block2header(b)
  File "/home/jeppa/Downloads/git/electrum-nmc-server/src/blockchain_processor.py", line 138, in block2header
    "bits": int(b.get('bits'), 16),
TypeError: int() can't convert non-string with explicit base

I don't know how to fix this.

**Comment by Kefkius** [comment]
The issue is that there are two possible namecoin daemons, the old one and the [reimplementation](https://github.com/namecoin/namecoin-core). Which are you using? The old version and the new version don't report the `bits` value in the same format.

Anyway, we can't have it only working for one of them. I'll look into both versions and change it to something that will work with them both.

**Comment by santzi** [comment]
I downloaded compiled binary for 14.04 Ubuntu (The version is namecoin_0.3.80-3.), because I have issue with compiling from sources:
"libbitcoin_common.a(libbitcoin_common_a-auxpow.o): In function `operator==':
/home/jeppa/Downloads/git/namecoin-core/src/./uint256.h:45: undefined reference to`CMerkleTx::ABANDON_HASH'
collect2: error: ld returned 1 exit status
make[2]: **\* [namecoind] Error 1"
Issue: https://github.com/namecoin/namecoin-core/issues/71

I have compiled BTC/LTC and other daemons without problems.

**Comment by santzi** [comment]
Just compiled new version namecoin daemon (nc0.12.0rc2). I'll try electrum server again soon.

**Comment by santzi** [comment]
Namecoin electrum server is now pruning phase. So this issue could be closed.
